<a href="https://colab.research.google.com/github/PSamita/Exoplanets/blob/main/Exoplanet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [26]:
# Create a dataframe planet1
p1 = {'Spectral Type': ['G'], 'Age of the System (Gyr)': [8.16], 'Binary System': ['Single Star'], 'Stellar Luminosities (Solar Units)': [1.32], 'Total Stellar Mass (Solar Masses)': [1.07], 'Stellar Radius (Solar Radii)': [1.07], 'Planet Orbital Period (Years)': [1.73], 'Planet Semi-Major Axis (AU)': [1.47], 'Planet Mass (Earth Masses)':[3.16], 'Planet Radius (Earth Radii)': [1.41], 'Eccentricity': [0.0954], 'N2': [84.376], 'CO2':[2.721], 'H2O': [0.511], 'O2': [12.393], 'Others':[0.000], 
      'Number of other (known) Planets in the System': [3], 'Location in the Galaxy': ['Disk'], 'Distance from Earth (lightyears)': [63.9], 'Atmospheric Pressure (atm)': [1.65], 'Planetary Albedo':[0.374], 'Planet Axial Tilt (degrees)': [21.2], 'Planet Rotation Period (Hours)': [20.2], 'Magnetic Field Strength (Units of Earth Magnetic Field)': [0.000663]}

planet1 = pd.DataFrame(data=p1)

planet1

,Spectral Type,Age of the System (Gyr),Binary System,Stellar Luminosities (Solar Units),Total Stellar Mass (Solar Masses),Stellar Radius (Solar Radii),Planet Orbital Period (Years),Planet Semi-Major Axis (AU),Planet Mass (Earth Masses),Planet Radius (Earth Radii),...,O2,Others,Number of other (known) Planets in the System,Location in the Galaxy,Distance from Earth (lightyears),Atmospheric Pressure (atm),Planetary Albedo,Planet Axial Tilt (degrees),Planet Rotation Period (Hours),Magnetic Field Strength (Units of Earth Magnetic Field)
0,G,8.16,Single Star,1.32,1.07,1.07,1.73,1.47,3.16,1.41,...,12.393,0.0,3,Disk,63.9,1.65,0.374,21.2,20.2,0.000663

In [27]:
# Create a dataframe planet2
p2 = {'Spectral Type': ['F'], 'Age of the System (Gyr)': [0.0568], 'Binary System': ['Single Star'], 'Stellar Luminosities (Solar Units)': [4.49], 'Total Stellar Mass (Solar Masses)': [1.46], 'Stellar Radius (Solar Radii)': [1.43], 'Planet Orbital Period (Years)': [4.81], 'Planet Semi-Major Axis (AU)': [3.23], 'Planet Mass (Earth Masses)':[3.07], 'Planet Radius (Earth Radii)': [1.47], 'Eccentricity': [0.11], 'N2': [88.003], 'CO2':[1.897], 'H2O': [4.838], 'O2': [5.261], 'Others':[0.000], 
      'Number of other (known) Planets in the System': [3], 'Location in the Galaxy': ['Open Cluster'], 'Distance from Earth (lightyears)': [1.58E+03], 'Atmospheric Pressure (atm)': [0.93], 'Magnetic Field Strength (Units of Earth Magnetic Field)': [1.2]}

planet2 = pd.DataFrame(data=p2)

planet2

,Spectral Type,Age of the System (Gyr),Binary System,Stellar Luminosities (Solar Units),Total Stellar Mass (Solar Masses),Stellar Radius (Solar Radii),Planet Orbital Period (Years),Planet Semi-Major Axis (AU),Planet Mass (Earth Masses),Planet Radius (Earth Radii),...,N2,CO2,H2O,O2,Others,Number of other (known) Planets in the System,Location in the Galaxy,Distance from Earth (lightyears),Atmospheric Pressure (atm),Magnetic Field Strength (Units of Earth Magnetic Field)
0,F,0.0568,Single Star,4.49,1.46,1.43,4.81,3.23,3.07,1.47,...,88.003,1.897,4.838,5.261,0.0,3,Open Cluster,1580.0,0.93,1.2

In [28]:
# Add a 'Planet' column to identify which planet each row belongs to
planet1.insert(0, "Planet", "Planet 1")
planet2.insert(0, "Planet", "Planet 2")

# Combine the two dataframes
planets = pd.concat([planet1, planet2], ignore_index=True)

In [29]:
# Add a column indicating whether each planet is a terrestrial planet
planets['Terrestrial Planet'] = np.where((planets['Planet Radius (Earth Radii)'] >= 0.5) & (planets['Planet Radius (Earth Radii)'] <= 2), 'Yes', 'No')

planets

,Planet,Spectral Type,Age of the System (Gyr),Binary System,Stellar Luminosities (Solar Units),Total Stellar Mass (Solar Masses),Stellar Radius (Solar Radii),Planet Orbital Period (Years),Planet Semi-Major Axis (AU),Planet Mass (Earth Masses),...,Others,Number of other (known) Planets in the System,Location in the Galaxy,Distance from Earth (lightyears),Atmospheric Pressure (atm),Planetary Albedo,Planet Axial Tilt (degrees),Planet Rotation Period (Hours),Magnetic Field Strength (Units of Earth Magnetic Field),Terrestrial Planet
0,Planet 1,G,8.1600,Single Star,1.32,1.07,1.07,1.73,1.47,3.16,...,0.0,3,Disk,63.9,1.65,0.374,21.2,20.2,0.000663,Yes
1,Planet 2,F,0.0568,Single Star,4.49,1.46,1.43,4.81,3.23,3.07,...,0.0,3,Open Cluster,1580.0,0.93,NaN,NaN,NaN,1.200000,Yes

In [30]:
# Add the habitable zone columns to the DataFrame
def habitable_zone(L):
    inner_bound = np.sqrt(L/1.1)
    outer_bound = np.sqrt(L/0.53)
    return inner_bound, outer_bound

planets['Inner Bound of Habitable Zone (AU)'], planets['Outer Bound of Habitable Zone (AU)'] = habitable_zone(planets['Stellar Luminosities (Solar Units)'])

planets

,Planet,Spectral Type,Age of the System (Gyr),Binary System,Stellar Luminosities (Solar Units),Total Stellar Mass (Solar Masses),Stellar Radius (Solar Radii),Planet Orbital Period (Years),Planet Semi-Major Axis (AU),Planet Mass (Earth Masses),...,Location in the Galaxy,Distance from Earth (lightyears),Atmospheric Pressure (atm),Planetary Albedo,Planet Axial Tilt (degrees),Planet Rotation Period (Hours),Magnetic Field Strength (Units of Earth Magnetic Field),Terrestrial Planet,Inner Bound of Habitable Zone (AU),Outer Bound of Habitable Zone (AU)
0,Planet 1,G,8.1600,Single Star,1.32,1.07,1.07,1.73,1.47,3.16,...,Disk,63.9,1.65,0.374,21.2,20.2,0.000663,Yes,1.095445,1.578153
1,Planet 2,F,0.0568,Single Star,4.49,1.46,1.43,4.81,3.23,3.07,...,Open Cluster,1580.0,0.93,NaN,NaN,NaN,1.200000,Yes,2.020351,2.910618

In [31]:
# Add a column indicating whether each planet is in the habitable zone
planets['In Habitable Zone'] = np.where((planets['Planet Semi-Major Axis (AU)'] >= planets['Inner Bound of Habitable Zone (AU)']) & (planets['Planet Semi-Major Axis (AU)'] <= planets['Outer Bound of Habitable Zone (AU)']), 'Yes', 'No')

planets

,Planet,Spectral Type,Age of the System (Gyr),Binary System,Stellar Luminosities (Solar Units),Total Stellar Mass (Solar Masses),Stellar Radius (Solar Radii),Planet Orbital Period (Years),Planet Semi-Major Axis (AU),Planet Mass (Earth Masses),...,Distance from Earth (lightyears),Atmospheric Pressure (atm),Planetary Albedo,Planet Axial Tilt (degrees),Planet Rotation Period (Hours),Magnetic Field Strength (Units of Earth Magnetic Field),Terrestrial Planet,Inner Bound of Habitable Zone (AU),Outer Bound of Habitable Zone (AU),In Habitable Zone
0,Planet 1,G,8.1600,Single Star,1.32,1.07,1.07,1.73,1.47,3.16,...,63.9,1.65,0.374,21.2,20.2,0.000663,Yes,1.095445,1.578153,Yes
1,Planet 2,F,0.0568,Single Star,4.49,1.46,1.43,4.81,3.23,3.07,...,1580.0,0.93,NaN,NaN,NaN,1.200000,Yes,2.020351,2.910618,No

In [32]:
from pandas.core.groupby.generic import SingleManager
import scipy.constants as const

sigma = const.sigma  # Stefan-Boltzmann constant

# Define a function to calculate the equilibrium temperature
def equilibrium_temp(L, a, albedo):
    return np.sqrt(np.sqrt(L * (1 - albedo) / (16 * sigma)) * (1 / np.sqrt(a)))

# Add the 'Equilibrium Temperature (K)' column to the DataFrame
planets['Equilibrium Temperature (K)'] = equilibrium_temp(planets['Stellar Luminosities (Solar Units)'], planets['Planet Semi-Major Axis (AU)'], planets['Planetary Albedo'])

planets

,Planet,Spectral Type,Age of the System (Gyr),Binary System,Stellar Luminosities (Solar Units),Total Stellar Mass (Solar Masses),Stellar Radius (Solar Radii),Planet Orbital Period (Years),Planet Semi-Major Axis (AU),Planet Mass (Earth Masses),...,Atmospheric Pressure (atm),Planetary Albedo,Planet Axial Tilt (degrees),Planet Rotation Period (Hours),Magnetic Field Strength (Units of Earth Magnetic Field),Terrestrial Planet,Inner Bound of Habitable Zone (AU),Outer Bound of Habitable Zone (AU),In Habitable Zone,Equilibrium Temperature (K)
0,Planet 1,G,8.1600,Single Star,1.32,1.07,1.07,1.73,1.47,3.16,...,1.65,0.374,21.2,20.2,0.000663,Yes,1.095445,1.578153,Yes,28.055939
1,Planet 2,F,0.0568,Single Star,4.49,1.46,1.43,4.81,3.23,3.07,...,0.93,NaN,NaN,NaN,1.200000,Yes,2.020351,2.910618,No,NaN